package com.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.daogenerator.AddressBook;

import com.daogenerator.AddressBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressBookDaoConfig;

    private final AddressBookDao addressBookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressBookDaoConfig = daoConfigMap.get(AddressBookDao.class).clone();
        addressBookDaoConfig.initIdentityScope(type);

        addressBookDao = new AddressBookDao(addressBookDaoConfig, this);

        registerDao(AddressBook.class, addressBookDao);
    }
    
    public void clear() {
        addressBookDaoConfig.getIdentityScope().clear();
    }

    public AddressBookDao getAddressBookDao() {
        return addressBookDao;
    }

}
